### ISSUE TITLE
animation stops when software is open and stop option is not showing 

### ISSUE THREAD

**Issue by Pirate6463** [Taiizor/Sucrose#84]

**Comment by Taiizor** [comment]
This is not an bug. Please review your Performance Settings. Because at least one of the performance conditions has been met, your wallpaper has been automatically paused.

If your wallpaper has been paused or closed according to your Performance Settings, you will not see the options to open or close wallpaper in the System Tray menus.

You can find detailed information about this topic in [this discussion](https://github.com/Taiizor/Sucrose/discussions/75).

**Comment by Taiizor** [comment]
I have made the necessary adjustments regarding this. It has become more informative compared to the previous version.

![Sucrose](https://github.com/Taiizor/Sucrose/assets/41683699/e00bf905-b22f-41a9-b642-4da36eb60b86)
![Sucrose](https://github.com/Taiizor/Sucrose/assets/41683699/213da23c-5930-4c84-b9f7-73076aabc357)

![Sucrose](https://github.com/Taiizor/Sucrose/assets/41683699/34cf31ef-4ec5-4944-846d-a9a96cf4731b)
![Sucrose](https://github.com/Taiizor/Sucrose/assets/41683699/3bdd51f9-9f3b-46a3-bc16-862264084fdd)

It will be active in the next released version of the application.

**Comment by Taiizor** [comment]
An update related to this has been released on the Developer channel. If you don't want to wait for the full release, you can change your Update Channel to Developer and then Check for Updates from the system tray.

![Sucrose](https://github.com/Taiizor/Sucrose/assets/41683699/8bb257c1-5fb5-4c67-93eb-e4705cf5a149)

![Sucrose](https://github.com/Taiizor/Sucrose/assets/41683699/be5eb378-1f5d-4fb1-bf00-52ea003b0de5)

**Comment by Taiizor** [comment]
@HanumanBhakt1 Could you confirm if your issue is related to this?
