### ISSUE TITLE
my app aint working

### ISSUE THREAD

**Issue by jalabbas313** [Taiizor/Sucrose#97]
**Bug Description**
the app isnt working but my wallpapers showing up i wanna change my wallpaper tho

**To Reproduce**

**Expected Behavior**
i eckckckcpexted for my acual app to work
**Screenshots/Video**
![image_2024-09-02_131342772](https://github.com/user-attachments/assets/050d87f5-5a59-4b0e-8bde-8a5ad14051a1

**Desktop (please complete the following information):**
 - OS: windows 11 home]
- any wallpaper running if any ![image_2024-09-02_131600459](https://github.com/user-attachments/assets/4270b227-b7aa-427a-88d5-f1a44f75ebdb)

**Additional Context**

**Log File (Important)**
Share the diagnostic files by:
Open Sucrose settings (Gear icon) top-right -> System -> Log Files -> Create
or 
Navigate to the Appdata folder `C:\Users\<UserName>\AppData\Roaming\Sucrose\Log`

**Comment by Taiizor** [comment]
![Sucrose-TrayIcon](https://github.com/user-attachments/assets/f747eaa7-9351-4e18-8e43-9300e7d472b8)

To open the application interface, right-click on the system tray as shown in the GIF file and select `Open Sucrose`. The application interface will then open as shown in the image below.

![Sucrose-Portal](https://github.com/user-attachments/assets/510a9eef-09cc-4ba7-891a-56597b167c7a)

If you are unable to open the interface and receive an error, this issue is likely related to another issue you opened (#96). Please follow the discussion there.
