### ISSUE TITLE
my sucrose, on the taskbar I will open the hidden icons, I right click on the sucrose and the open wallpaper button and it says (closed) ,and when I open the sucrose menu I click on my wallpapers and it doesn't appear.help me!

### ISSUE THREAD

**Issue by xguihackerhax** [Taiizor/Sucrose#98]
![imagem_2024-09-20_093542076](https://github.com/user-attachments/assets/6f88c1f4-05a5-4d55-ad88-f990cb7cdb60)

**Comment by xguihackerhax** [comment]
and when I open the sucrose menu I click on my wallpapers and it doesn't appear.

**Comment by Taiizor** [comment]
Oh, the reason for this is that a condition in your performance settings has been met. Review your settings under performance where 'Close' has been selected.

![Sucrose-Performance-Settings](https://github.com/user-attachments/assets/a32b3d9a-cfaf-4abc-9131-30a5b48c8650)

If it has been closed due to performance conditions, it will display 'Closed'. If it has been paused, it will display 'Paused'.

**Comment by Taiizor** [comment]
@xguihackerhax Did you understand?

**Comment by xguihackerhax** [comment]
Oh,thanks!
